- lib/lotus/helpers.rb
- lib/lotus/helpers/escape_helper.rb
- test/escape_helper_test.rb
- test/fixtures.rb
> Added escape helpers

- lib/lotus/helpers.rb
- lib/lotus/helpers/numbers.rb
- lib/lotus/helpers/numbers/number_formatter.rb
- test/fixtures.rb
- test/numbers_test.rb
Number formatting helper as discussed in https://github.com/lotus/helpers/issues/3
Closes #3
> Number formatting helper

- Gemfile
- lib/lotus/helpers/form_helper.rb
- lib/lotus/helpers/form_helper/form_builder.rb
- lib/lotus/helpers/form_helper/html_node.rb
- test/fixtures.rb
- test/form_helper_test.rb
- test/integration/form_helper_test.rb
> CSRF Protection support for lotusrb

- lib/lotus/helpers/form_helper.rb
- lib/lotus/helpers/form_helper/form_builder.rb
- test/fixtures.rb
- test/form_helper_test.rb
> Add text_area helper to form_for

- CHANGELOG.md
- lib/lotus/helpers/form_helper/form_builder.rb
- test/form_helper_test.rb
> Form #label outputs capitalized strings

- lib/lotus/helpers/form_helper/form_builder.rb
- test/form_helper_test.rb
> Add number field to form builder.

- Gemfile
- LICENSE.md
- test/test_helper.rb
:tada: :star2: :christmas_tree:
> Update copyright to 2016 year

- Gemfile
- LICENSE.md
- test/test_helper.rb
> Revert "Update copyright to 2016 year"

- .travis.yml
> Added rbx2 to travis

- lib/hanami/helpers/html_helper/html_builder.rb
- lib/hanami/helpers/link_to_helper.rb
- test/fixtures.rb
- test/html_helper_test.rb
> Revert "Link to in html"

- hanami-helpers.gemspec
- lib/hanami/helpers/form_helper/form_builder.rb
- lib/hanami/helpers/html_helper/empty_html_node.rb
/cc @hanami/core-team @hanami/contributors
> Fix Ruby warnings

- test/integration/form_helper_test.rb
This test is about re-rendering the form when a field was emptied.
* the parameter sent by rack would be an empty string and not nil
* the form should not re-fill the field (especially if it's not the field causing the error)
> Fix blank submission test

- hanami-helpers.gemspec
- lib/hanami/helpers/form_helper/values.rb
- test/fixtures.rb
- test/form_helper_test.rb
- test/integration/html_helper_test.rb
Apparent regression in Hanami 0.9.x series.
Alternative solution to #86
Fixes #84
> Fix FormBuilder populating form values (alternative)

- lib/hanami/helpers/form_helper/form_builder.rb
- test/form_helper_test.rb
- test/test_helper.rb
With this test I get an error 
```
NoMethodError: undefined method `include?' for true:TrueClass
helpers/lib/hanami/helpers/form_helper/form_builder.rb:1036:in `_attributes_for_check_box'
```
I guess this include? is for multiple checkboxes, it also works with string values like '1' or 'true' from params, but I pass model with boolean attributes to form. May be there should be a check that value is an array?
> Checkbox behaves unexpectedly when passing a boolean in values

- lib/hanami/helpers/form_helper/form_builder.rb
- test/form_helper_test.rb
Extracted from other [PR](https://github.com/hanami/helpers/pull/73). Tests state the problem. I don't know whether `to_s` is best solution, anyone has any ideas?
> Radiobuttons and selects values that are not strings

- lib/hanami/helpers.rb
- lib/hanami/helpers/form_helper.rb
- lib/hanami/helpers/form_helper/form_builder.rb
- lib/hanami/helpers/html_helper.rb
- lib/hanami/helpers/html_helper/empty_html_node.rb
- lib/hanami/helpers/html_helper/html_builder.rb
- lib/hanami/helpers/html_helper/html_fragment.rb
- lib/hanami/helpers/routing_helper.rb
```shell
➜ bundle exec yardoc --no-cache --no-save --protected --private --no-api private --markup markdown lib
Files:          10
Modules:         8 (    0 undocumented)
Classes:         3 (    0 undocumented)
Constants:       1 (    0 undocumented)
Attributes:      0 (    0 undocumented)
Methods:        33 (    0 undocumented)
100.00% documented
```
> API docs cleanup

- lib/hanami/helpers/form_helper/form_builder.rb
- test/fixtures.rb
- test/form_helper_test.rb
This PR introduces new form helpers:
* `image_button` (`<input type="image">`)
* `range_field` (`<input type="range">`)
* `search_field` (`<input type="search">`)
* `url_field` (`<input type="url">`)
* `tel_field` (`<input type="tel">`)
> Update form elements

- lib/hanami/helpers/html_helper/html_builder.rb
- test/html_helper/html_builder_test.rb
https://developer.mozilla.org/en-US/docs/Web/HTML/Element
> Update HTML elements

- .circleci/config.yml
- .jrubyrc
- .travis.yml
- Gemfile
- README.md
- Rakefile
- script/ci
- spec/spec_helper.rb
- spec/support/rspec.rb
> Code quality tools

- hanami-helpers.gemspec
- lib/hanami/helpers/form_helper/form_builder.rb
- spec/unit/hanami/helpers/form_helper_spec.rb
> Add support for block syntax in label helper
