hanami/helpers

.travis.yml
* also added rbx-2 as most other components have it
* allowing failures
`jruby-head` fails as `Binding#receiver` seems to be unimplemented, see jruby/jruby#2578
=> Add jruby-head and rbx-2 to .travis.yml

lib/lotus/helpers.rb, lib/lotus/helpers/link_to_helper.rb, test/fixtures.rb, test/fixtures/templates/link_to/index.html.erb, test/integration/link_to_helper_test.rb, test/link_to_helper_test.rb
LinkTo Helper
===========
Provides a helper method for generating links. As dicussed on [discuss.lotusrb.org #58](https://discuss.lotusrb.org/t/link-to-view-helper/58)
link_to 'blogs', :blogs_path
link_to 'archives', '/archives', class: archives
=> Add link_to helper

test/integration/routing_helper_test.rb
Since the problem does not occur on all  platforms (i.e. not on CI) i assume that the line ending is handled differently.
=> Fixes failed routing helper integration test

lib/lotus/helpers/link_to_helper.rb, test/fixtures.rb, test/fixtures/templates/link_to/index.html.erb, test/integration/link_to_helper_test.rb, test/link_to_helper_test.rb
Improve support for html content in link_to helper
```ruby
link_to(nil, routes.path(:posts)) do
strong 'Post'
end
```
```ruby
link_to(routes.path(:posts)) do
strong 'Post'
end
```
=> Improve link_to with html content param

lib/lotus/helpers/html_helper/empty_html_node.rb, test/form_helper_test.rb, test/html_helper/html_builder_test.rb
Boolean attributes are rendered differently than normal attributes.
If its value is _false_ then the whole attribute is omitted.
If its value is _true_ then the attribute is rendered with its name as the value.
+ added special handling of boolean attributes
+ added tests
! fixed existing tests that checked for „true“ values in rendered boolean attributes
=> Added support for boolean attributes.

lib/lotus/helpers/html_helper/html_builder.rb, lib/lotus/helpers/html_helper/text_node.rb, test/html_helper/html_builder_test.rb
This feature allows for more complex structures to be defined. One example is the one of a label with a radio button or a checkbox:
```ruby
builder.label do
text "Option 1"
radio_button :option, 1
end
```
=> Add support for text inside other tags.

lib/lotus/helpers/form_helper/form_builder.rb, test/form_helper_test.rb
Relates to #32.
In the scenario of having extra HTML attributes without some content being
passed in, the attributes hash was being set to nil while the content variable
holding the attributes hash.
In the scenario:
```ruby
form_for :book do
text_area :description, rows: 5
end
```
The `content` argument was `{ rows: 5 }` and `attributes` was `{}`.
This is still a pretty ugly solution. I need some feedback on this.
=> Fix attribution of HTML attributes.

lib/lotus/helpers/form_helper/form_builder.rb, test/form_helper_test.rb
I made this little change to prevent FormHelper to inject the csrf_token hidden field on GET requests, like search forms or button links.
Please consider to merge to master. Tks
=> FormBuilder doesn't inject hidden fields on GET requests

lib/lotus/helpers/form_helper/form_builder.rb
Applying feedback from this https://github.com/lotus/helpers/pull/39
@joneslee85 @jodosha for now, I changed to `verb_method`, because I don't figured out why the `@verb` variable was defined only on `_method_override!`. If it was defined before the `to_s` method, a lot os tests was broken... Maybe this was a smell to refactoring how the `@verb` variable should be handled.
Thanks
=> Renaming method to verb_method on FormBuilder

lib/lotus/helpers/html_helper/html_builder.rb
I noticed HtmlBuilder not have definition list element 'dd'.
http://www.w3.org/TR/html4/struct/lists.html#h-10.3
I think it is required.
=> Add definition list element 'dd'

lib/lotus/helpers/html_helper.rb, lib/lotus/helpers/html_helper/html_builder.rb, lib/lotus/helpers/html_helper/html_fragment.rb, test/fixtures.rb, test/html_helper/html_builder_test.rb, test/html_helper_test.rb
Hello @lotus,
I would like to propose html fragment (or maybe another better name) which will be useful to avoid html string concatenation like
```ruby
html.div("Hello") + html.div("Lotus") + html.div("Ruby")
#=> <div>Hello</div><div>Lotus</div><div>Ruby</div>
```
It looks much better to me with html fragment declaration, especially nested HTML.
```ruby
html do
div "Hello"
div "Lotus"
div "Ruby"
end
```
=> Propose html fragment

lib/hanami/helpers/html_helper/html_builder.rb, lib/hanami/helpers/link_to_helper.rb, test/fixtures.rb, test/html_helper_test.rb
Fixed #48
Also I fixed case when `html` helper called inside another `html` helper. For example:
``` ruby
html.div do
span 'hello'
html.div { span 'hanami' }
end
```
/cc @hanami/core-team
=> Link to in html

lib/hanami/helpers/link_to_helper.rb, test/fixtures.rb, test/html_helper_test.rb, test/link_to_helper_test.rb
=> Allow links to be concat

lib/hanami/helpers/form_helper/form_builder.rb, test/form_helper_test.rb
Adding `datalist` form helper, fix #57 
```html
<input list="browsers" name="browser">
<datalist id="browsers">
<option value="Internet Explorer">
<option value="Firefox">
<option value="Chrome">
<option value="Opera">
<option value="Safari">
</datalist>
```
The only problem I think we need to fix is about `option` tag, it's `CONTENT_TAGS` on `html_builder.rb` so that it will have close tag.
This is my first pull request for Ruby/Hanami (I just learned Ruby about 3 months ago and didn't work much with it). Please let me know if there's anything wrong.
Thank you.
P/S: sorry for my bad English.
=> adding datalist form helper

lib/hanami/helpers/form_helper/form_builder.rb, test/fixtures.rb, test/form_helper_test.rb
**This is a breaking change proposal. If approved, we have to bump the minor version to `v0.4.0`.**
---
The `values` has must to be composed with: keys as `value` attribute and values as content of the `<option>` tag.
```erb
<%=
values = Hash['it' => 'Italy', 'us' => 'United States']
select :stores, values
%>
```
```html
<select name="book[store]" id="book-store">
<option value="it">Italy</option>
<option value="us">United States</option>
</select>
```
The `values` has must to be composed with: values as `value` attribute and keys as content of the `<option>` tag.
```erb
<%=
values = Hash['Italy' => 'it', 'United States' => 'us']
select :stores, values
%>
```
```html
<select name="book[store]" id="book-store">
<option value="it">Italy</option>
<option value="us">United States</option> …
```
=> Invert values for form builder's select

CHANGELOG.md, lib/hanami/helpers/html_helper/html_fragment.rb, lib/hanami/helpers/html_helper/html_node.rb, lib/hanami/helpers/html_helper/text_node.rb, lib/hanami/helpers/number_formatting_helper.rb, lib/hanami/helpers/routing_helper.rb
Thank you for such an awesome tool. I'm using `hanami-helpers` within a `middleman` project, and occasionally ran into dependency issues with some of the helpers.
=> Explicitly require some hanami-utils dependencies

Rakefile, lib/hanami/helpers/form_helper/form_builder.rb, test/form_helper_test.rb
This is the implementation for https://github.com/hanami/helpers/issues/66.
It enables to set the selected option if one of the option values matches the passed entity's attribute:
`select :author, authors, selected: book.id`
=> Set selected option based on entity's attribute

.rubocop.yml, lib/hanami/helpers/form_helper/values.rb, test/fixtures.rb
This is useful to support unit tests setup in Hanami projects, when
developers wants to pass pure Hash to simulate params, instead of an
instance of `Hanami::Action::Params`.
Ref https://github.com/hanami/helpers/issues/71#issuecomment-239104711
=> Form values to support `Hash#dig`

lib/hanami/helpers/routing_helper.rb, lib/hanami/helpers/version.rb, test/fixtures.rb, test/version_test.rb
The next version of Hanami will expose application routes via `Web.routes` instead of `Web::Routes`.
=> New routes factory

lib/hanami/helpers/form_helper/form_builder.rb, test/form_helper_test.rb
We can't ATM have a fully working select that can select multiple values.
This PR adds this use case to the `select` helper
=> add multiple option possibility to select

lib/hanami/helpers/number_formatting_helper.rb, test/fixtures.rb, test/number_formatting_helper_test.rb
This fixes https://github.com/hanami/helpers/issues/77
New method is only applied when precision is explicitly passed in options. It does not use default precision for that, because it would be backwards incompatible.
I didn't include solution for secon issue from #77, as I belier pull requests should be atomic. The issue was:
> One detail left: in case of an integer, user friendly use would be to have a default precision to 0, to avoid having format_number(1000) == "1,000.00" instead of "1,000"
=> Fix number formatting precision

lib/hanami/helpers/number_formatting_helper.rb
> I have just noticed a shameful typo in my code, where method is named precision_requested_explicity? instead of precision_requested_explicitly?. 
> Can some maintainer fix it maybe, please? 😉
From https://github.com/hanami/helpers/pull/85#issuecomment-262731624
:)
=> Fix typo: explicity => explicitly

lib/hanami/helpers/form_helper/form_builder.rb
You can see that in documentation we call `stores` instead `store`
http://www.rubydoc.info/gems/hanami-helpers/Hanami/Helpers/FormHelper/FormBuilder#select-instance_method
/cc @hanami/documentation
=> Fix typo in select documentation

lib/hanami/helpers/form_helper/form_builder.rb, test/form_helper_test.rb, test/html_helper/html_builder_test.rb
Closes https://github.com/hanami/hanami/issues/709
=> Form helper doesn't escape value attribute for values entities

lib/hanami/helpers/html_helper/html_builder.rb
We support Ruby 2.3+. Remove a load time check to define a method.
=> Remove Ruby 2.2 load check

lib/hanami/helpers/form_helper/form_builder.rb
The hash parameter used to determine the contents of a `select` node has an unexpected format, cf issue #118. This commit makes the documentation consistent with how the `select` method currently works.
=> Fix the documentation of the `select` helper method.

lib/hanami/helpers/form_helper/form_builder.rb, spec/unit/hanami/helpers/form_helper_spec.rb
Hi,
This PR is an attempt to improve the documentation of the `select` form helper:
- it describes more thoroughly what the `values` parameter is,
- it fixes an error where two examples were inverted,
- it adds an example with an `Array` as input,
- it adds a spec to ensure that repeated entries are allowed.
The case for using something else than a `Hash` as input can be made on the ground that in some cases, it might be better for user convenience to be able to repeat entries in a select. One case could be country selection, where a handful of favourite countries are displayed first, and then the whole list (without trying to remove the favourites from that whole list).
=> Documentation of the `select` helper

lib/hanami/helpers/html_helper/empty_html_node.rb, lib/hanami/helpers/html_helper/html_node.rb, spec/unit/hanami/helpers/html_helper/html_builder_spec.rb
Without this change, `class: [:ui, :form]` renders, in HTML, as:
```html
class="["ui", "form"]
```
which is not what a developer would expect.
With this change, `class: [:ui, :form]` renders, in HTML, as:
```html
class="ui form"
```
as one would expect.
Note: I implemented this for _all_ attributes, not just `class`. I'm not sure if that makes sense? I can't think of other attributes that would act this way.
If we only want to do this for `class`, it actually makes the code more perform better, since we don't have to go through the process of iterating through the Hash and creating a new copy of it.
I also only wrote the spec for `input`, but we should have it for all the attributes. Just wanted to make sure others were interested in this change before I went through the manual work for …
=> Join attribute values with space, for arrays

lib/hanami/helpers/form_helper/form_builder.rb, spec/unit/hanami/helpers/form_helper_spec.rb
Fixes #131
@nerdinand can you take a look this fix?
@jodosha I was playing with this bug and decided to make the first contribution 🎉 
The bug was originated because of the `selected` been set as `nil` and the first value been `nil` as well.
If we are happy with the end result I would like to refactor `_select_option_selected?` before merging.
=> fix select with values and nil options

.gitignore, lib/hanami/helpers/form_helper/form_builder.rb, spec/integration/form_helper_spec.rb, spec/support/fixtures.rb, spec/support/fixtures/templates/bills/edit2.html.erb
Fixes #121 
This is just a first pass at implementing this. Any feedback is welcome.
One problem I faced was that `fields_for_collection` actually already passes an argument to the block: The index of the element in the collection. In order to not break the existing API I added the new `value` block parameter at second place.
=> fields_for_collection: pass resource in block

lib/hanami/helpers/form_helper/form_builder.rb, spec/unit/hanami/helpers/form_helper_spec.rb
Bug introduced in Hanami 1.2 PR #132
This avoids select element not having a selected option when comparing 5 (String) to 5 (Integer), for example.
=> FormBuilder: fixing method _select_option_selected?

lib/hanami/helpers/form_helper.rb, spec/unit/hanami/helpers/form_helper_spec.rb
`value` isn't a valid attribute for a meta tag, according to [the spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta), we want `content` instead.
Discovered this because I was trying to use `hanami-ujs` and it wasn't picking the CSRF meta tag values properly, since it looks for the `content` attribute. I'm using this branc now and it solved the problem. :)
Fixes bug introduced in: #129 
(Intentionally opened against `master` instead of `develop` since this PR is fixing a bug, which can be a patch release.)
=> Change CSRF meta tag from 'value' to 'content'

lib/hanami/helpers/form_helper/form_builder.rb, spec/unit/hanami/helpers/form_helper_spec.rb
Without this attribute Hanami will treat "Select store...", for example, as the value and add it to the params.
=> Adds a disabled attribute to the select option prompt

lib/hanami/helpers/form_helper.rb, lib/hanami/helpers/form_helper/form_builder.rb, spec/unit/hanami/helpers/form_helper_spec.rb
Make possible for `#form_for` to accept `params:` a keyword argument to override params coming from the view context.
This enhancement provides the ultimate flexibility for people who want to take control on form rendering.
---
Closes https://github.com/hanami/helpers/issues/149
=> `#form_for` allow to pass params inline
